version: '3.3'
services:

  database:
    image: 'postgres:15.2'
    container_name: database
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=sample-db
