version: '3.3'
services:

  database:
    image: postgres
    container_name: database
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=sample-db
      - PGDATA=/var/lib/postgresql/data/pgdata

volumes:
  postgres_data:
    driver: local